package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"magic-helper/graph/gentypes"
	"magic-helper/graph/model"
	"magic-helper/graph/mtg"
)

// Mutation resolvers delegate to the mtg package which holds domain logic.
// This layer remains thin, mapping GraphQL to service functions.
// CreateMTGDeck is the resolver for the createMTGDeck field.
func (r *mutationResolver) CreateMTGDeck(ctx context.Context, input model.MtgCreateDeckInput) (*model.Response, error) {
	return mtg.CreateMTGDeck(ctx, input)
}

// DeleteMTGDeck is the resolver for the deleteMTGDeck field.
func (r *mutationResolver) DeleteMTGDeck(ctx context.Context, input model.MtgDeleteDeckInput) (*model.Response, error) {
	return mtg.DeleteMTGDeck(ctx, input)
}

// UpdateMTGDeck is the resolver for the updateMTGDeck field.
func (r *mutationResolver) UpdateMTGDeck(ctx context.Context, input model.MtgUpdateDeckInput) (*model.Response, error) {
	return mtg.UpdateMTGDeck(ctx, input)
}

// SaveMTGDeckAsCopy is the resolver for the saveMTGDeckAsCopy field.
func (r *mutationResolver) SaveMTGDeckAsCopy(ctx context.Context, input model.MtgUpdateDeckInput) (*model.Response, error) {
	return mtg.SaveMTGDeckAsCopy(ctx, input)
}

// CreateMTGFilterPreset is the resolver for the createMTGFilterPreset field.
func (r *mutationResolver) CreateMTGFilterPreset(ctx context.Context, input model.MtgCreateFilterPresetInput) (*model.MtgFilterPreset, error) {
	return mtg.CreateMTGFilterPreset(ctx, input)
}

// UpdateMTGFilterPreset is the resolver for the updateMTGFilterPreset field.
func (r *mutationResolver) UpdateMTGFilterPreset(ctx context.Context, input model.MtgUpdateFilterPresetInput) (*model.MtgFilterPreset, error) {
	return mtg.UpdateMTGFilterPreset(ctx, input)
}

// DeleteMTGFilterPreset is the resolver for the deleteMTGFilterPreset field.
func (r *mutationResolver) DeleteMTGFilterPreset(ctx context.Context, input model.MtgDeleteFilterPresetInput) (*model.Response, error) {
	return mtg.DeleteMTGFilterPreset(ctx, input)
}

// AddIgnoredCard is the resolver for the addIgnoredCard field.
func (r *mutationResolver) AddIgnoredCard(ctx context.Context, input model.AddIgnoredCardInput) (*model.Response, error) {
	return mtg.AddIgnoredCard(ctx, input)
}

// RemoveIgnoredCard is the resolver for the removeIgnoredCard field.
func (r *mutationResolver) RemoveIgnoredCard(ctx context.Context, input model.RemoveIgnoredCardInput) (*model.Response, error) {
	return mtg.RemoveIgnoredCard(ctx, input)
}

// CreateMTGTag is the resolver for the createMTGTag field.
func (r *mutationResolver) CreateMTGTag(ctx context.Context, input model.MtgCreateTagInput) (*model.MtgTag, error) {
	return mtg.CreateMTGTag(ctx, input)
}

// UpdateMTGTag is the resolver for the updateMTGTag field.
func (r *mutationResolver) UpdateMTGTag(ctx context.Context, input model.MtgUpdateTagInput) (*model.MtgTag, error) {
	return mtg.UpdateMTGTag(ctx, input)
}

// DeleteMTGTag is the resolver for the deleteMTGTag field.
func (r *mutationResolver) DeleteMTGTag(ctx context.Context, input model.MtgDeleteTagInput) (*model.Response, error) {
	return mtg.DeleteMTGTag(ctx, input)
}

// AssignTagToCard is the resolver for the assignTagToCard field.
func (r *mutationResolver) AssignTagToCard(ctx context.Context, input model.MtgAssignTagToCardInput) (*model.Response, error) {
	return mtg.AssignTagToCard(ctx, input)
}

// UnassignTagFromCard is the resolver for the unassignTagFromCard field.
func (r *mutationResolver) UnassignTagFromCard(ctx context.Context, input model.MtgUnassignTagFromCardInput) (*model.Response, error) {
	return mtg.UnassignTagFromCard(ctx, input)
}

// AssignTagToDeck is the resolver for the assignTagToDeck field.
func (r *mutationResolver) AssignTagToDeck(ctx context.Context, input model.MtgAssignTagToDeckInput) (*model.Response, error) {
	return mtg.AssignTagToDeck(ctx, input)
}

// UnassignTagFromDeck is the resolver for the unassignTagFromDeck field.
func (r *mutationResolver) UnassignTagFromDeck(ctx context.Context, input model.MtgUnassignTagFromDeckInput) (*model.Response, error) {
	return mtg.UnassignTagFromDeck(ctx, input)
}

// Mutation returns gentypes.MutationResolver implementation.
func (r *Resolver) Mutation() gentypes.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
