package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"magic-helper/graph/gentypes"
	"magic-helper/graph/model"
	"magic-helper/graph/mtga"
)

// GetMTGACards is the resolver for the getMTGACards field.
func (r *queryResolver) GetMTGACards(ctx context.Context) ([]*model.MtgaCard, error) {
	return mtga.GetMTGACards(ctx)
}

// GetMTGAFilters is the resolver for the getMTGAFilters field.
func (r *queryResolver) GetMTGAFilters(ctx context.Context) (*model.MtgaFilterEntries, error) {
	return mtga.GetMTGAFilters(ctx)
}

// GetMTGADecks is the resolver for the getMTGADecks field.
func (r *queryResolver) GetMTGADecks(ctx context.Context, deckID *string) ([]*model.MtgaDeck, error) {
	return mtga.GetMTGADecks(ctx, deckID)
}

// Query returns gentypes.QueryResolver implementation.
func (r *Resolver) Query() gentypes.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
