package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"magic-helper/graph/gentypes"
	"magic-helper/graph/model"
)

// GetCards is the resolver for the getCards field.
func (r *queryResolver) GetCards(ctx context.Context) ([]*model.MtgaCard, error) {
	panic(fmt.Errorf("not implemented: GetCards - getCards"))
}

// Query returns gentypes.QueryResolver implementation.
func (r *Resolver) Query() gentypes.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
