package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"magic-helper/graph/gentypes"
	"magic-helper/graph/model"
	"magic-helper/graph/mtg"
)

// GetMTGCards is the resolver for the getMTGCards field.
func (r *queryResolver) GetMTGCards(ctx context.Context) ([]*model.MtgCard, error) {
	return mtg.GetMTGCards(ctx)
}

// GetMTGFilters is the resolver for the getMTGFilters field.
func (r *queryResolver) GetMTGFilters(ctx context.Context) (*model.MtgFilterEntries, error) {
	return mtg.GetMTGFilters(ctx)
}

// GetMTGDecks is the resolver for the getMTGDecks field.
func (r *queryResolver) GetMTGDecks(ctx context.Context, deckID *string) ([]*model.MtgDeck, error) {
	return mtg.GetMTGDecks(ctx, deckID)
}

// GetMTGCardPackages is the resolver for the getMTGCardPackages field.
func (r *queryResolver) GetMTGCardPackages(ctx context.Context, cardPackageID *string) ([]*model.MtgCardPackage, error) {
	return mtg.GetMTGCardPackages(ctx, cardPackageID)
}

// Query returns gentypes.QueryResolver implementation.
func (r *Resolver) Query() gentypes.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
