image: gitpod/workspace-full

tasks:
    - init: |
          sudo docker-up
    - command: |
          docker-compose up --build

ports:
    - port: 3000
      onOpen: open-preview
    - port: 8529
      onOpen: open-preview
