version: '3.8'
services:
    arangodb:
        container_name: arangodb
        image: arangodb
        restart: always
        volumes:
            - ./arangodb/data:/var/lib/arangodb3
            - ./arangodb/apps:/var/lib/arangodb3-apps
            - ./backup/:/backupcms2/
            - ./dumps/:/dumps
        environment:
            ARANGO_ROOT_PASSWORD: arangodb #TODO: please CHANGE this password
        networks:
            - rockboard_net
        ports:
            - 8529:8529
networks:
    rockboard_net:
