version: '3.8'
services:
    arangodb_magic_helper:
        container_name: arangodb_magic_helper
        image: arangodb
        restart: always
        volumes:
            - ./arangodb/data:/var/lib/arangodb3
            - ./arangodb/apps:/var/lib/arangodb3-apps
            - ./backup/:/backupcms2/
            - ./dumps/:/dumps
        environment:
            ARANGO_ROOT_PASSWORD: arangodb #TODO: please CHANGE this password
        networks:
            - magic-helper-net
        ports:
            - 8530:8529
networks:
    magic-helper-net:
